# TCL File Generated by Component Editor 21.1
# Tue Jun 21 18:24:36 CEST 2022
# DO NOT MODIFY


# 
# AvalonST_AXI4_Stream_Bridge "AvalonST_AXI4_Stream_Bridge" v1.0
#  2022.06.21.18:24:36
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AvalonST_AXI4_Stream_Bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME AvalonST_AXI4_Stream_Bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME AvalonST_AXI4_Stream_Bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_axi4stream_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon-axi4stream-interconnect.sv SYSTEM_VERILOG PATH AvalonST_AXI4Stream/avalon-axi4stream-interconnect.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_axi4stream_bridge
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon-axi4stream-interconnect.sv SYSTEM_VERILOG PATH AvalonST_AXI4Stream/avalon-axi4stream-interconnect.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avalon_axi4stream_bridge
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon-axi4stream-interconnect.sv SYSTEM_VERILOG PATH AvalonST_AXI4Stream/avalon-axi4stream-interconnect.sv


# 
# parameters
# 
add_parameter FIFO_WIDTH INTEGER 2
set_parameter_property FIFO_WIDTH DEFAULT_VALUE 2
set_parameter_property FIFO_WIDTH DISPLAY_NAME FIFO_WIDTH
set_parameter_property FIFO_WIDTH TYPE INTEGER
set_parameter_property FIFO_WIDTH UNITS None
set_parameter_property FIFO_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_WIDTH HDL_PARAMETER true
add_parameter FIFO_DEPTH INTEGER 10
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 10
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock aclk
set_interface_property avalon_slave associatedReset rst
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave address address Input 16
add_interface_port avalon_slave readdata readdata Output FIFO_WIDTH*8
add_interface_port avalon_slave writedata writedata Input FIFO_WIDTH*8
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave waitrequest waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point aclk
# 
add_interface aclk clock end
set_interface_property aclk clockRate 0
set_interface_property aclk ENABLED true
set_interface_property aclk EXPORT_OF ""
set_interface_property aclk PORT_NAME_MAP ""
set_interface_property aclk CMSIS_SVD_VARIABLES ""
set_interface_property aclk SVD_ADDRESS_GROUP ""

add_interface_port aclk aclk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock aclk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point axi4stream_slave
# 
add_interface axi4stream_slave axi4stream end
set_interface_property axi4stream_slave associatedClock aclk
set_interface_property axi4stream_slave associatedReset rst
set_interface_property axi4stream_slave ENABLED true
set_interface_property axi4stream_slave EXPORT_OF ""
set_interface_property axi4stream_slave PORT_NAME_MAP ""
set_interface_property axi4stream_slave CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_slave SVD_ADDRESS_GROUP ""

add_interface_port axi4stream_slave oAXI_valid tvalid Input 1
add_interface_port axi4stream_slave oAXI_ready tready Output 1
add_interface_port axi4stream_slave oAXI_data tdata Input FIFO_WIDTH*8


# 
# connection point axi4stream_master
# 
add_interface axi4stream_master axi4stream start
set_interface_property axi4stream_master associatedClock aclk
set_interface_property axi4stream_master associatedReset rst
set_interface_property axi4stream_master ENABLED true
set_interface_property axi4stream_master EXPORT_OF ""
set_interface_property axi4stream_master PORT_NAME_MAP ""
set_interface_property axi4stream_master CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_master SVD_ADDRESS_GROUP ""

add_interface_port axi4stream_master iAXI_valid tvalid Output 1
add_interface_port axi4stream_master iAXI_data tdata Output FIFO_WIDTH*8
add_interface_port axi4stream_master iAXI_ready tready Input 1
add_interface_port axi4stream_master iAXI_tuser tuser Output 1

