# TCL File Generated by Component Editor 21.1
# Tue Jun 21 18:14:30 CEST 2022
# DO NOT MODIFY


# 
# AXI_FIFO "AXI_FIFO" v1.0
#  2022.06.21.18:14:30
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AXI_FIFO
# 
set_module_property DESCRIPTION ""
set_module_property NAME AXI_FIFO
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME AXI_FIFO
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AXI_FIFO
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FIFO.sv SYSTEM_VERILOG PATH AXI_FIFO/FIFO.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL AXI_FIFO
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FIFO.sv SYSTEM_VERILOG PATH AXI_FIFO/FIFO.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL AXI_FIFO
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file FIFO.sv SYSTEM_VERILOG PATH AXI_FIFO/FIFO.sv


# 
# parameters
# 
add_parameter FIFO_WIDTH INTEGER 2
set_parameter_property FIFO_WIDTH DEFAULT_VALUE 2
set_parameter_property FIFO_WIDTH DISPLAY_NAME FIFO_WIDTH
set_parameter_property FIFO_WIDTH TYPE INTEGER
set_parameter_property FIFO_WIDTH UNITS None
set_parameter_property FIFO_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_WIDTH HDL_PARAMETER true
add_parameter FIFO_DEPTH INTEGER 10
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 10
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point axi4stream_master
# 
add_interface axi4stream_master axi4stream start
set_interface_property axi4stream_master associatedClock aclk
set_interface_property axi4stream_master associatedReset rst
set_interface_property axi4stream_master ENABLED true
set_interface_property axi4stream_master EXPORT_OF ""
set_interface_property axi4stream_master PORT_NAME_MAP ""
set_interface_property axi4stream_master CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_master SVD_ADDRESS_GROUP ""

add_interface_port axi4stream_master oAXI_data tdata Output 8*FIFO_WIDTH
add_interface_port axi4stream_master oAXI_ready tready Input 1
add_interface_port axi4stream_master oAXI_valid tvalid Output 1


# 
# connection point aclk
# 
add_interface aclk clock end
set_interface_property aclk clockRate 0
set_interface_property aclk ENABLED true
set_interface_property aclk EXPORT_OF ""
set_interface_property aclk PORT_NAME_MAP ""
set_interface_property aclk CMSIS_SVD_VARIABLES ""
set_interface_property aclk SVD_ADDRESS_GROUP ""

add_interface_port aclk aclk clk Input 1


# 
# connection point oAXI_aclk
# 
add_interface oAXI_aclk clock start
set_interface_property oAXI_aclk associatedDirectClock ""
set_interface_property oAXI_aclk clockRate 0
set_interface_property oAXI_aclk clockRateKnown false
set_interface_property oAXI_aclk ENABLED true
set_interface_property oAXI_aclk EXPORT_OF ""
set_interface_property oAXI_aclk PORT_NAME_MAP ""
set_interface_property oAXI_aclk CMSIS_SVD_VARIABLES ""
set_interface_property oAXI_aclk SVD_ADDRESS_GROUP ""

add_interface_port oAXI_aclk oAXI_aclk clk Output 1


# 
# connection point axi4stream_slave
# 
add_interface axi4stream_slave axi4stream end
set_interface_property axi4stream_slave associatedClock iAXI_aclk
set_interface_property axi4stream_slave associatedReset rst
set_interface_property axi4stream_slave ENABLED true
set_interface_property axi4stream_slave EXPORT_OF ""
set_interface_property axi4stream_slave PORT_NAME_MAP ""
set_interface_property axi4stream_slave CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_slave SVD_ADDRESS_GROUP ""

add_interface_port axi4stream_slave iAXI_data tdata Input 8*FIFO_WIDTH
add_interface_port axi4stream_slave iAXI_ready tready Output 1
add_interface_port axi4stream_slave iAXI_valid tvalid Input 1
add_interface_port axi4stream_slave iAXI_tuser tuser Input 1


# 
# connection point iAXI_aclk
# 
add_interface iAXI_aclk clock end
set_interface_property iAXI_aclk clockRate 0
set_interface_property iAXI_aclk ENABLED true
set_interface_property iAXI_aclk EXPORT_OF ""
set_interface_property iAXI_aclk PORT_NAME_MAP ""
set_interface_property iAXI_aclk CMSIS_SVD_VARIABLES ""
set_interface_property iAXI_aclk SVD_ADDRESS_GROUP ""

add_interface_port iAXI_aclk iAXI_aclk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock aclk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1

